### PR TITLE
Adding support for money[]

### PR DESCRIPTION
**Pull request by vitaly-t**
This is to address issue https://github.com/brianc/node-postgres/issues/781

### CODE REVIEW

**Comment by brianc** [comment]
Hey sorry I missed this.

Could you write some tests to support this as well?  Once it has tests I'll happily merge it & push a new version.

**Comment by bendrucker** [comment]
This shouldn't be the default parser. If your database is localized to use a different prefix this breaks. Almost certain you can't rely on a single character either. The only change that should be implemented here is to add a text array parser here.

**Comment by vitaly-t** [comment]
@bendrucker , this however remains to be a bug. The library should be able to convert `money[]` correctly.

**Comment by bendrucker** [comment]
http://www.postgresql.org/docs/9.1/static/datatype-money.html

> Input is accepted in a variety of formats, including integer and floating-point literals, as well as typical currency formatting, such as '$1,000.00'. Output is generally in the latter form but depends on the locale.

Your solution would create an array of `NaN` if the database were localized to another currency. The money type can also exceed JS integer safety. You can override the parser since you may know that neither of these apply to your data, but the library can't make assumptions.

**Pull request closed without merging**
