### PR TITLE
update TS definitions to be in sync with implementation

### LINKED ISSUE #98: Wrong and too strict TS type definitions
TS type definitions were [added recently](https://github.com/brianc/node-pg-types/commit/8e73b4645e7d26f9d91f195c63fdf98a0a1decb7) in version 2.2.0.

However, there is already an existing [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pg-types/index.d.ts) version of them.

They are different and definitely typed version is better to use for us. ISo I would suggest merge of them together.

Differences (issues in new type definitions):

1. Missing `TypeParser` type for parsing function
2. Too strict `oid: TypeId` which does not allow custom DB types which might have any number
3. Wrong `arrayParser` type definition that does not respect the implementation (Definitely Typed definition does)

### PR DESCRIPTION
**Pull request by stekycz**
Fixes #98

### CODE REVIEW

**Comment by stekycz** [comment]
There is one remaining issue I know about related to the array parser. The array parser might parse recursive array with the expected type in leaves. However, the depth of the array recursiveness depends on the input string. That is why multidimensional array will be typed as single-dimensional. 

Do you have some suggestion on how to type it? I do not want to use `ReadonlyArray<any>` and using generic recursivity breaks typing for the most common usage (IMO) - single-dimensional array.

**Comment by bendrucker** [comment]
Thanks! I have minimal TypeScript experience so I can't give you much guidance about the nested array question.

**Comment by stekycz** [comment]
No problem. I will think about it more and I will send another PR if I will came with something.

**Comment by bendrucker** [comment]
Is this ok to merge as is? Wasn't sure based on your question.

**Comment by stekycz** [comment]
Yes, feel free to merge it 👍

**Pull request merged**
