### PR TITLE
Fix truncation of BIGINT within nested JSON

### PR DESCRIPTION
**Pull request by philberg**
Currently, this library does not parse INT by default given that it will truncate a BIGINT of full size.

However, in the case of nested JSON columns, the string from postgres is being passed straight into JSON.parse, which immediately truncates the values.  Other than overriding JSON.parse (a terrible choice), my solution is to do a string replace on the JSON string to convert the integer values into strings.

Unfortunately, there isn't really a good way to check if this process even needs to occur before it does, so it will lead to a slight performance degradation.  It also causes an API level behavioral change

### CODE REVIEW

**Comment by philberg** [comment]
@brianc would love to get some feedback on this...  If you don't intend to include this or a similar change into the project I need to know ASAP, so I can approach it differently as it's currently breaking our system

**Comment by bendrucker** [comment]
I don't think this is the right solution. As I see it, the best approach here is to not make a special exception for JSON. If you plan to store values that can't be properly parsed with default JS behavior in JSON, you should be overriding the JSON parser and parsing manually.

**Comment by philberg** [comment]
The objects are being created with the JSON builder functions in postgres, so they are using BIGINT fields that would otherwise be returned as strings if they weren't nested.

I looked into the native JSON.parse code, and eventually, the string just [gets passed directly into the native `eval function`](https://github.com/douglascrockford/JSON-js/blob/master/json2.js#L504).  Overriding this wouldn't make any sense given that it's likely to be compiled C code.  

Another option would be to use the alternative parser, which [explicitly parses each value](https://github.com/douglascrockford/JSON-js/blob/master/json_parse.js#L142).  It's possible to do a quick check to make sure the parsed value is less than the overflow value and if not, keep it as a string.  I would recommend that at a library level we do one or the other, given that it's corrupting data in its current state, and we can't guarantee that JSON objects were saved to postgres by a javascript library.

**Comment by bendrucker** [comment]
Still disagree that this is a library concern. When you use normal columns, PG reports the types. When you use JSON, there is no type info. I think the default behavior should be to use JSON.parse and then the user can override if they know there may be types in their JSON that JS doesn't support.

**Comment by philberg** [comment]
I understand the lack of type definition, but it doesn't change the fact that leaving it as is means that the main node-postgres library will automagically truncate values that people aren't expecting.  This will be especially frustrating when migrating from another language and could potentially lead to major confusion.

This issue was already resolved with regular INT values, and it was decided that the default behavior would be to preserve the values, and leave it optional to parse... I would highly recommend we maintain the same behavior with arrays, json, etc.

Whether or not you decide the default behavior should be the same, we should make it easy for the user to override the parser at the library level only, as to not disturb the rest of their project with unintended consequences if they so choose.

**Comment by bendrucker** [comment]
Seems like the best resolution here is to publish your code as a strict json parser so it's easy for people to override if needed

**Comment by brianc** [comment]
I agree w/ @bendrucker this is better suited as another module you can require & hook into the type parsing system standalone - that's kinda why we made the type parsing system extensible, so you can modify things that you don't agree with in your app.  In general it seems like a risky idea to store 64 bit numbers as _numbers_ in a json data structure, regardless of language used to create/parse the json.  I appreciate the effort you went through - good news its it should be really easy to pop that out into another module you can wire up!

**Pull request closed without merging**
