### PR TITLE
Added parser registration for JSONB array

### PR DESCRIPTION
**Pull request by chung-leong**
In regards to https://github.com/brianc/node-postgres/issues/775.

### CODE REVIEW

**Comment by nilshartmann** [comment]
fyi: tested your change, works fine!

**Comment by kamholz** [comment]
Can we get this merged and released? I'd like to make use of it. Thanks!

**Comment by bendrucker** [comment]
How did I come up with an oid of 3802 while you have 3807? Traveling this week but still expecting to find time to get all issues/PRs closed out. If you have ideas re: the oid it'lll save me a few mins, otherwise I'll investigate.

**Comment by kamholz** [comment]
The oid of jsonb is 3802. The oid of jsonb[] is 3807. Different types, different oids, and both should be supported. :-)

**Comment by bendrucker** [comment]
Right you are @kamholz. Just read the diff wrong on my PR. This is a dupe of #21.

**Comment by kamholz** [comment]
Thanks for merging this in @bendrucker. Just wondering now when it will be released so I can remove the reference to a GitHub repo from my package.json. :-)

**Comment by bendrucker** [comment]
Sure! I've got a bit more clean up work to do here. When it's all done we'll cut a release.

**Pull request closed without merging**
