### PR TITLE
typos in textParser.js

### PR DESCRIPTION
**Pull request by keithwhor**
:fire: Fixed some breaking typos and standardizes variable names (val -> value in all cases).

### CODE REVIEW

**Comment by bendrucker** [comment]
Please remove the commit changing the version. Will get this merged.

**Comment by keithwhor** [comment]
Can do.

**Comment by bendrucker** [comment]
Please just remove both and squash down to a single commit

**Comment by keithwhor** [comment]
commits are mixed, i'll close this PR and open a new one.

**Pull request closed without merging**
