### PR TITLE
Parse jsonb array columns

### PR DESCRIPTION
**Pull request by bendrucker**
Per https://github.com/brianc/node-postgres/pull/456#issuecomment-75909527

### CODE REVIEW

**Comment by macobo** [comment]
:+1:

**Comment by bendrucker** [comment]
@brianc if you wanna add me as a collab i'm happy to get all the issues/prs solved here before we move on to the harder core stuff

**Comment by brianc** [comment]
@bendrucker absolutely would love to do that! Dang there are a lot of PRs sitting in here...my bad!  I'm on vacay until tomorrow but I'll try & jump on some of this stuff too & try & help out later the week.  Please feel free to do whatever you want w/ regards to collab! :heart:

**Comment by bendrucker** [comment]
No worries. Will give everything a nice fresh coat of paint while you're :sunglasses: :ocean: :shell:

**Comment by brianc** [comment]
:dancer: :clap:

**Pull request closed without merging**
