### PR TITLE
Update deps, require node 8

### LINKED ISSUE #104: Error with Buffer() Deprecated
Hello,

First of all, thank you for your work!

You have a dependency to  "postgres-bytea": "~1.0.0". It seems that dependency make an error in aws lambda due to Buffer deprecated constructor.

Perhaps you could update your dependency to version 2.0.0 to resolve this issue?

Thank you!

### PR DESCRIPTION
**Pull request by bendrucker**
This would require a major version bump, which I think we should be doing anyway as numeric/binary oriented changes have been piling up in master. @brianc are you ok with going ahead with a major release of node-postgres as well? Node 4's EOL was about 1.5 years ago. 8's is coming up (December). 

Closes #104

### CODE REVIEW

**Comment by charmander** [comment]
Breaking changes also worth considering for a major release:

- integer types as `BigInt` instead of string for much better type safety (requires Node 10, so maybe not if this is targeted at Node 8) (#78)

- no date parsing for `date` and (maybe?) `timestamp without time zone` (#50, #81)

- removal of `lib/arrayParser.js`

**Comment by bendrucker** [comment]
I think we should just get a major release out and evaluate dates and big ints for a later major. We haven't been doing many of these releases. Removing `lib/arrayParser.js` seems easy/uncontroversial.

@brianc Thoughts on doing a major release for Node 8 and then doing a future major for Node 12 that incorporates BigInt + Date changes?

**Comment by brianc** [comment]
> Thoughts on doing a major release for Node 8 and then doing a future major for Node 12 that incorporates BigInt + Date changes?

Yeah I'm down with that.  You want a major bump in node-posgres core as well right?  I can sweep in a couple other breaking changes we wanted to make too.

**Comment by bendrucker** [comment]
> You want a major bump in node-posgres core as well right?

Yup, major bump here, and then a major bump in node-postgres updating the dep.

**Comment by bendrucker** [comment]
Finally took the time to merge this and release 3.0 to npm. Happy to take on further breaking changes in 4.0 which might be node 12+ assuming it comes early 2020.

@brianc Do you need any help landing other changes to node-postgres? If not I can just open the PR bumping the pg-types dep and setting `engines.node`.

**Comment by gajus** [comment]
What is the correct way to parse the array now?

This broke https://github.com/gajus/slonik/issues/182

**Comment by gajus** [comment]
This is how I fixed it https://github.com/gajus/slonik/commit/042669dab03421e18e8dda270c92a4089cbdedd7, but not sure if that was the expected way.

**Comment by charmander** [comment]
@gajus That works, yes. You can also write `parseArray(arrayValue, typeParser.parse)`.

**Pull request merged**
