### PR TITLE
Register oid array to be parsed as integer array

### PR DESCRIPTION
**Pull request by mnahkies**
Add OID[] as a type registered to be parsed, using the integer array parser

### CODE REVIEW

**Comment by mnahkies** [comment]
@brianc The Travis CI build has failed, but I believe this is a pre-existing issue rather than caused by my change. Any chance you could take a look?

**Comment by bendrucker** [comment]
Looks like `buffer.equals` is being called somewhere. If I remember right that's not in Node 0.10. Updating Travis to do Node 0.12 and 5.

**Comment by mnahkies** [comment]
@bendrucker: I've merged your travis-ci change into my branch and the build is now passing, thanks. 

Does this mean that pg should be considered incompatible with node < 0.12? 

If so the package.json should probably be updated to reflect this: https://github.com/brianc/node-postgres/blob/master/package.json#L41

**Comment by bendrucker** [comment]
The tests don't guarantee compatibility but it's still compatible

**Pull request closed without merging**
